// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rmznrafianrqxlefkjuu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJtem5yYWZpYW5ycXhsZWZranV1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY2MjkwMTcsImV4cCI6MjA2MjIwNTAxN30.hcuprlUF1f2lrte6hObEw01IPPMORk107P3eDPOiUCs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);